apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgDG9seOUyvJVpcXDHyUCos19dKHlYhrktGlAbcFqSCEc83KmPCMCW8hUR7HXyW/dPtxQb/jvDkfI+qvuSSY90kOkx53bjYZ7BSyKeWwJBAUgXoN6e2jglux+Roz7nKLOn/9tlfAzLrx1Ryoxv/rY3WFTi6AoEm+TMlBOonrshBvyAa0vJQMuKxDO/V8SPiWuW70po696fe4hqCOAz9/IRACPfH4v6FvbvVCmAvynALsiauGBLPKGebXo8fRNx/KueLyI7+cJkTdy9Gn7/VcVqLPexxdtpy/r2vVRlG+BsSoMkSUJWw+ijdoi8/W7FPqyvFviJ8FYLfWRM517jvkWBwKiCr4lrUCtuh/G1/cufFMh9etNONrq7zWMIMnkJKjOvmmJ//ZmcbltRYT7dTlP7e6PLqojHTzF8TqaxkIsRF1o7VBnqt7Cvw6nZCwnrRpHeHiQiFoErxVnHyz/2xaX/sQz+Kko+bR/5+8Tw5Ij5vdnS2ZIFZmIv4n7LtzPjDaA+ebmqN91957k5wl6MO6kapm6riQfeWkukawkmRGci/Ainem47YIZcNwknKnlF4SLgfMyLyNpqduDqSPmRfAW9QGD+jm7AmId3Vx4CKXvtfithMhBDwTxKLWSIr5LACKamlnog+HWHT/idWGSqVG0BgIx730qvmn99TTLmzru3/gHevy/hfbd3FYkErALpH+GMBYGNWMKVFwjw==
    DB_USER: AgCqfHijVC16fdFMN18v06AFvdcozrizsHFmSYa2APTNYYmu9NHKWVQLe/7ay+33WrkQRHN5MdQ+3Ki7+/7kgQI6I9V3llN9NYbOkTbH4wIJwCuePpr+kFukVSe6sCuKExETT2/bexRaGE2horMuhqMHXiWlljEIKJrgJ4GN+Os0CpscQ9XgsFw2PAfntXh7a2fgjH9OVOmI57VYk+/2lBPOAxViX56H+EsJ1MrHQQt/BIEOlmFxHemjG5Cq9iI3H5O+CB+Ahn8SmD8c5krZuK6qO20zUUiLtrAPN7o/5ZvfAOFwqIMv42I33SbqQhLi5OZ1o6+Xv46XyVS1fmEwt+udUf2g1/nnSRMLOXuwl0TmzZWGH7IRkO20hDiENYAz18q1m8zVAtx4wM6cXoPS0ZTzOxDALK1zxBxBQV8vwW6+Pqhh4D9Sjs6OXQomaXvwOqCI3+XohCPDQmSI+kZzon+Ds3ElrTotjJJeuBogkUKmnehxfFVhQyH63o0lNDOixG+S+iqOLL9lXF4+4ks5ys/hF+NcGdckhOcwhDkIUaOc2Df3rQVcQqoVOmax15zUvw5fWMnT9MweJMApUWvX8wxulQH19Ql53GIGBAelaBS7cglxkcIhr8RG8LWxR6Dl55aUtlY+L39h3FM54mdFeY6xrVuF0f0g8f/BaRE7j+JZYpMnKYMn19lIEN+d9BciRglR1kQYYRe8Ig==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

